#ifndef IPT2SOCKS_UDP_PROXY_H
#define IPT2SOCKS_UDP_PROXY_H

/* ── udp_proxy.h ───────────────────────────────────────────────────────────
 * All UDP-proxy protocol types live here.
 * ──────────────────────────────────────────────────────────────────────── */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "ev_types.h"

#include "lrucache.h"   /* myhash_hh, MYLRU_HASH_*, LRU_DEFINE_*  */
#include "netutils.h"   /* ip_port_t                           */

/* ════════════════════════════════════════════════════════════════════════
 * Cache Capacity API
 * ════════════════════════════════════════════════════════════════════════ */

uint16_t udp_lrucache_get_main_maxsize(void);
uint16_t udp_lrucache_get_fork_maxsize(void);
uint16_t udp_lrucache_get_tproxy_maxsize(void);
void udp_lrucache_set_maxsize(uint16_t base_size);

/* ════════════════════════════════════════════════════════════════════════
 * Memory-pool / queue constants
 * ════════════════════════════════════════════════════════════════════════ */

#define MEMPOOL_BLOCK_SIZE    2048
#define MEMPOOL_INITIAL_SIZE  256

#define UDP_QUEUE_MAX_DEPTH   16
#define UDP_BATCH_SIZE        16

#define MAX_DOMAIN_LEN        255
#define MAX_SOCKS5_UDP_HEADER 262

#define SOCKS5_RESPONSE_MAX_SIZE 32

/* ════════════════════════════════════════════════════════════════════════
 * Pending-packet queue  (used during SOCKS5 handshake)
 * ════════════════════════════════════════════════════════════════════════ */

typedef struct udp_packet_node {
    struct udp_packet_node *next;
    size_t                  len;
    uint8_t                 data[];   /* flexible-array payload */
} udp_packet_node_t;

typedef struct {
    udp_packet_node_t *head;
    udp_packet_node_t *tail;
    size_t             count;
} udp_packet_queue_t;

/* ════════════════════════════════════════════════════════════════════════
 * Cache key types
 * ════════════════════════════════════════════════════════════════════════ */

/*
 * udp_fork_key_t — composite key for the Fork Table.
 * Identifies a unique (client, target) pair for Symmetric NAT splitting.
 */
typedef struct {
    ip_port_t client_ipport;
    bool      target_is_ipv4;   /* protocol-family flag for target */
    ip_port_t target_ipport;    /* full address for Symmetric NAT  */
} udp_fork_key_t;

/* ════════════════════════════════════════════════════════════════════════
 * udp_socks5ctx_t  — session context for the Main Table and Fork Table
 *
 * One struct participates in both tables (keyed by key_ipport or fork_key).
 * The `is_forked` flag records which table currently owns the entry.
 * ════════════════════════════════════════════════════════════════════════ */

typedef struct {
    /* ── cache keys ────────────────────────────────── */
    ip_port_t      key_ipport;   /* Main Table key: client source IP:Port  */
    udp_fork_key_t fork_key;     /* Fork Table key: (client, target) pair  */

    /* ── session metadata ──────────────────────────── */
    ip_port_t      orig_dstaddr; /* original destination (FakeIP or real)  */
    bool           dest_is_ipv4; /* protocol-family flag for orig_dstaddr  */
    bool           is_forked;    /* true ⟹ entry lives in Fork Table       */
    bool           is_fakedns;   /* true ⟹ FakeDNS session                 */

    /* ── libev watchers ────────────────────────────── */
    evio_t    tcp_watcher;  /* no longer uses .data for handshake buf */
    evio_t    udp_watcher;  /* .data → &pending_queue (handshake) | NULL (fwd)    */
    evtimer_t idle_timer;

    /* ── SOCKS5 handshake state ─────────────────────── */
    union {
        uint8_t handshake_buf[32];
        struct {
            uint16_t nbytes;    /* current nsend or nrecv */
            uint16_t step_len;  /* expected packet size for this phase */
            uint8_t  payload[28];
        } handshake;
    };

    /* ── pending packet queue (buffered during handshake) ── */
    udp_packet_queue_t pending_queue;

    /* ── uthash bookkeeping (must be last) ─────────── */
    myhash_hh hh;
} udp_socks5ctx_t;

/* ════════════════════════════════════════════════════════════════════════
 * udp_tproxyctx_t  — per-source-socket context for the TProxy Table
 * ════════════════════════════════════════════════════════════════════════ */

typedef struct {
    ip_port_t key_ipport;   /* (remote) source socket address */
    int       udp_sockfd;   /* bound to the above address      */
    evtimer_t idle_timer;

    myhash_hh hh;           /* uthash bookkeeping              */
} udp_tproxyctx_t;

/* ════════════════════════════════════════════════════════════════════════
 * LRU cache function declarations
 * (bodies generated by LRU_DEFINE_* in udp_lrucache.c)
 * ════════════════════════════════════════════════════════════════════════ */

/* add — returns the evicted (LRU) entry when over capacity, else NULL */
udp_socks5ctx_t* udp_socks5ctx_add(udp_socks5ctx_t **cache, udp_socks5ctx_t *entry);
udp_socks5ctx_t* udp_socks5ctx_fork_add(udp_socks5ctx_t **cache, udp_socks5ctx_t *entry);
udp_tproxyctx_t* udp_tproxyctx_add(udp_tproxyctx_t **cache, udp_tproxyctx_t *entry);

/* get — lookup + bump to MRU end; returns NULL on miss */
udp_socks5ctx_t* udp_socks5ctx_get(udp_socks5ctx_t **cache, const ip_port_t      *keyptr);
udp_socks5ctx_t* udp_socks5ctx_fork_get(udp_socks5ctx_t **cache, const udp_fork_key_t *keyptr);
udp_tproxyctx_t* udp_tproxyctx_get(udp_tproxyctx_t **cache, const ip_port_t      *keyptr);

/* find — pure lookup, no LRU bump; for batch hot paths */
udp_socks5ctx_t* udp_socks5ctx_find(udp_socks5ctx_t **cache, const ip_port_t      *keyptr);
udp_socks5ctx_t* udp_socks5ctx_fork_find(udp_socks5ctx_t **cache, const udp_fork_key_t *keyptr);
udp_tproxyctx_t* udp_tproxyctx_find(udp_tproxyctx_t **cache, const ip_port_t      *keyptr);

/* del — unconditional removal */
void udp_socks5ctx_del(udp_socks5ctx_t **cache, udp_socks5ctx_t *entry);
void udp_tproxyctx_del(udp_tproxyctx_t **cache, udp_tproxyctx_t *entry);

/*
 * touch — bump an existing entry to the MRU end.
 *
 * Generated by LRU_DEFINE_TOUCH in udp_lrucache.c.
 */
void udp_socks5ctx_touch_main(udp_socks5ctx_t **cache, udp_socks5ctx_t *entry);
void udp_socks5ctx_touch_fork(udp_socks5ctx_t **cache, udp_socks5ctx_t *entry);
void udp_tproxyctx_touch(udp_tproxyctx_t **cache, udp_tproxyctx_t *entry);

/*
 * clear — iterate over all entries and invoke a callback, safe for removal.
 *
 * Generated by LRU_DEFINE_CLEAR in udp_lrucache.c.
 */
typedef void (*udp_socks5ctx_cb_t)(void *ctx, udp_socks5ctx_t *entry);
typedef void (*udp_tproxyctx_cb_t)(void *ctx, udp_tproxyctx_t *entry);

void udp_socks5ctx_clear_main(udp_socks5ctx_t **cache, udp_socks5ctx_cb_t cb, void *ctx);
void udp_socks5ctx_clear_fork(udp_socks5ctx_t **cache, udp_socks5ctx_cb_t cb, void *ctx);
void udp_tproxyctx_clear(udp_tproxyctx_t **cache, udp_tproxyctx_cb_t cb, void *ctx);

/* ════════════════════════════════════════════════════════════════════════
 * Event callbacks
 * ════════════════════════════════════════════════════════════════════════ */

void udp_tproxy_recvmsg_cb(evloop_t *evloop, struct ev_watcher *watcher, int revents);
void udp_proxy_close_all_sessions(evloop_t *evloop);

#endif /* IPT2SOCKS_UDP_PROXY_H */
